/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumsResponse {
    #[serde(rename = "defaultAssetOrder")]
    pub default_asset_order: models::AssetOrder,
}

impl AlbumsResponse {
    pub fn new(default_asset_order: models::AssetOrder) -> AlbumsResponse {
        AlbumsResponse {
            default_asset_order,
        }
    }
}

