/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumsAddAssetsResponseDto {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::BulkIdErrorReason>,
    /// Operation success
    #[serde(rename = "success")]
    pub success: bool,
}

impl AlbumsAddAssetsResponseDto {
    pub fn new(success: bool) -> AlbumsAddAssetsResponseDto {
        AlbumsAddAssetsResponseDto {
            error: None,
            success,
        }
    }
}

