/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumsAddAssetsDto {
    /// Album IDs
    #[serde(rename = "albumIds")]
    pub album_ids: Vec<uuid::Uuid>,
    /// Asset IDs
    #[serde(rename = "assetIds")]
    pub asset_ids: Vec<uuid::Uuid>,
}

impl AlbumsAddAssetsDto {
    pub fn new(album_ids: Vec<uuid::Uuid>, asset_ids: Vec<uuid::Uuid>) -> AlbumsAddAssetsDto {
        AlbumsAddAssetsDto {
            album_ids,
            asset_ids,
        }
    }
}

