/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlbumsUpdate : Album preferences
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumsUpdate {
    #[serde(rename = "defaultAssetOrder", skip_serializing_if = "Option::is_none")]
    pub default_asset_order: Option<models::AssetOrder>,
}

impl AlbumsUpdate {
    /// Album preferences
    pub fn new() -> AlbumsUpdate {
        AlbumsUpdate {
            default_asset_order: None,
        }
    }
}

