/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponseDto {
    /// Creation date
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// API key ID
    #[serde(rename = "id")]
    pub id: String,
    /// API key name
    #[serde(rename = "name")]
    pub name: String,
    /// List of permissions
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::Permission>,
    /// Last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ApiKeyResponseDto {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, name: String, permissions: Vec<models::Permission>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> ApiKeyResponseDto {
        ApiKeyResponseDto {
            created_at,
            id,
            name,
            permissions,
            updated_at,
        }
    }
}

