/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetUploadAction : Upload action
/// Upload action
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetUploadAction {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "reject")]
    Reject,

}

impl std::fmt::Display for AssetUploadAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Accept => write!(f, "accept"),
            Self::Reject => write!(f, "reject"),
        }
    }
}

impl Default for AssetUploadAction {
    fn default() -> AssetUploadAction {
        Self::Accept
    }
}

