/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadataBulkDeleteDto {
    /// Metadata items to delete
    #[serde(rename = "items")]
    pub items: Vec<models::AssetMetadataBulkDeleteItemDto>,
}

impl AssetMetadataBulkDeleteDto {
    pub fn new(items: Vec<models::AssetMetadataBulkDeleteItemDto>) -> AssetMetadataBulkDeleteDto {
        AssetMetadataBulkDeleteDto {
            items,
        }
    }
}

