/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetIdErrorReason : Error reason if failed
/// Error reason if failed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetIdErrorReason {
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "no_permission")]
    NoPermission,
    #[serde(rename = "not_found")]
    NotFound,

}

impl std::fmt::Display for AssetIdErrorReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Duplicate => write!(f, "duplicate"),
            Self::NoPermission => write!(f, "no_permission"),
            Self::NotFound => write!(f, "not_found"),
        }
    }
}

impl Default for AssetIdErrorReason {
    fn default() -> AssetIdErrorReason {
        Self::Duplicate
    }
}

