/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetStatsResponseDto {
    /// Number of images
    #[serde(rename = "images")]
    pub images: i32,
    /// Total number of assets
    #[serde(rename = "total")]
    pub total: i32,
    /// Number of videos
    #[serde(rename = "videos")]
    pub videos: i32,
}

impl AssetStatsResponseDto {
    pub fn new(images: i32, total: i32, videos: i32) -> AssetStatsResponseDto {
        AssetStatsResponseDto {
            images,
            total,
            videos,
        }
    }
}

