/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadataUpsertItemDto {
    /// Metadata key
    #[serde(rename = "key")]
    pub key: String,
    /// Metadata value (object)
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl AssetMetadataUpsertItemDto {
    pub fn new(key: String, value: std::collections::HashMap<String, serde_json::Value>) -> AssetMetadataUpsertItemDto {
        AssetMetadataUpsertItemDto {
            key,
            value,
        }
    }
}

