/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetEditsCreateDto {
    /// List of edit actions to apply (crop, rotate, or mirror)
    #[serde(rename = "edits")]
    pub edits: Vec<models::AssetEditActionItemDto>,
}

impl AssetEditsCreateDto {
    pub fn new(edits: Vec<models::AssetEditActionItemDto>) -> AssetEditsCreateDto {
        AssetEditsCreateDto {
            edits,
        }
    }
}

