/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadataBulkUpsertItemDto {
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: uuid::Uuid,
    /// Metadata key
    #[serde(rename = "key")]
    pub key: String,
    /// Metadata value (object)
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl AssetMetadataBulkUpsertItemDto {
    pub fn new(asset_id: uuid::Uuid, key: String, value: std::collections::HashMap<String, serde_json::Value>) -> AssetMetadataBulkUpsertItemDto {
        AssetMetadataBulkUpsertItemDto {
            asset_id,
            key,
            value,
        }
    }
}

