/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetIdsResponseDto {
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: String,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::AssetIdErrorReason>,
    /// Whether operation succeeded
    #[serde(rename = "success")]
    pub success: bool,
}

impl AssetIdsResponseDto {
    pub fn new(asset_id: String, success: bool) -> AssetIdsResponseDto {
        AssetIdsResponseDto {
            asset_id,
            error: None,
            success,
        }
    }
}

