/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetEditAction : Type of edit action to perform
/// Type of edit action to perform
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetEditAction {
    #[serde(rename = "crop")]
    Crop,
    #[serde(rename = "rotate")]
    Rotate,
    #[serde(rename = "mirror")]
    Mirror,

}

impl std::fmt::Display for AssetEditAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Crop => write!(f, "crop"),
            Self::Rotate => write!(f, "rotate"),
            Self::Mirror => write!(f, "mirror"),
        }
    }
}

impl Default for AssetEditAction {
    fn default() -> AssetEditAction {
        Self::Crop
    }
}

