/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetJobsDto {
    /// Asset IDs
    #[serde(rename = "assetIds")]
    pub asset_ids: Vec<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: models::AssetJobName,
}

impl AssetJobsDto {
    pub fn new(asset_ids: Vec<uuid::Uuid>, name: models::AssetJobName) -> AssetJobsDto {
        AssetJobsDto {
            asset_ids,
            name,
        }
    }
}

