/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetCopyDto {
    /// Copy album associations
    #[serde(rename = "albums", skip_serializing_if = "Option::is_none")]
    pub albums: Option<bool>,
    /// Copy favorite status
    #[serde(rename = "favorite", skip_serializing_if = "Option::is_none")]
    pub favorite: Option<bool>,
    /// Copy shared links
    #[serde(rename = "sharedLinks", skip_serializing_if = "Option::is_none")]
    pub shared_links: Option<bool>,
    /// Copy sidecar file
    #[serde(rename = "sidecar", skip_serializing_if = "Option::is_none")]
    pub sidecar: Option<bool>,
    /// Source asset ID
    #[serde(rename = "sourceId")]
    pub source_id: uuid::Uuid,
    /// Copy stack association
    #[serde(rename = "stack", skip_serializing_if = "Option::is_none")]
    pub stack: Option<bool>,
    /// Target asset ID
    #[serde(rename = "targetId")]
    pub target_id: uuid::Uuid,
}

impl AssetCopyDto {
    pub fn new(source_id: uuid::Uuid, target_id: uuid::Uuid) -> AssetCopyDto {
        AssetCopyDto {
            albums: None,
            favorite: None,
            shared_links: None,
            sidecar: None,
            source_id,
            stack: None,
            target_id,
        }
    }
}

