/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetRejectReason : Rejection reason if rejected
/// Rejection reason if rejected
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetRejectReason {
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "unsupported-format")]
    UnsupportedFormat,

}

impl std::fmt::Display for AssetRejectReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Duplicate => write!(f, "duplicate"),
            Self::UnsupportedFormat => write!(f, "unsupported-format"),
        }
    }
}

impl Default for AssetRejectReason {
    fn default() -> AssetRejectReason {
        Self::Duplicate
    }
}

