/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadataBulkResponseDto {
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: String,
    /// Metadata key
    #[serde(rename = "key")]
    pub key: String,
    /// Last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Metadata value (object)
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl AssetMetadataBulkResponseDto {
    pub fn new(asset_id: String, key: String, updated_at: chrono::DateTime<chrono::FixedOffset>, value: std::collections::HashMap<String, serde_json::Value>) -> AssetMetadataBulkResponseDto {
        AssetMetadataBulkResponseDto {
            asset_id,
            key,
            updated_at,
            value,
        }
    }
}

