/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetOrderBy : Asset sorting property
/// Asset sorting property
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetOrderBy {
    #[serde(rename = "takenAt")]
    TakenAt,
    #[serde(rename = "createdAt")]
    CreatedAt,

}

impl std::fmt::Display for AssetOrderBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TakenAt => write!(f, "takenAt"),
            Self::CreatedAt => write!(f, "createdAt"),
        }
    }
}

impl Default for AssetOrderBy {
    fn default() -> AssetOrderBy {
        Self::TakenAt
    }
}

