/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthStatusResponseDto {
    /// Session expiration date
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// Is elevated session
    #[serde(rename = "isElevated")]
    pub is_elevated: bool,
    /// Has password set
    #[serde(rename = "password")]
    pub password: bool,
    /// Has PIN code set
    #[serde(rename = "pinCode")]
    pub pin_code: bool,
    /// PIN expiration date
    #[serde(rename = "pinExpiresAt", skip_serializing_if = "Option::is_none")]
    pub pin_expires_at: Option<String>,
}

impl AuthStatusResponseDto {
    pub fn new(is_elevated: bool, password: bool, pin_code: bool) -> AuthStatusResponseDto {
        AuthStatusResponseDto {
            expires_at: None,
            is_elevated,
            password,
            pin_code,
            pin_expires_at: None,
        }
    }
}

