/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkIdErrorReason : Error reason
/// Error reason
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BulkIdErrorReason {
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "no_permission")]
    NoPermission,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "validation")]
    Validation,

}

impl std::fmt::Display for BulkIdErrorReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Duplicate => write!(f, "duplicate"),
            Self::NoPermission => write!(f, "no_permission"),
            Self::NotFound => write!(f, "not_found"),
            Self::Unknown => write!(f, "unknown"),
            Self::Validation => write!(f, "validation"),
        }
    }
}

impl Default for BulkIdErrorReason {
    fn default() -> BulkIdErrorReason {
        Self::Duplicate
    }
}

