/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CastResponse {
    /// Whether Google Cast is enabled
    #[serde(rename = "gCastEnabled")]
    pub g_cast_enabled: bool,
}

impl CastResponse {
    pub fn new(g_cast_enabled: bool) -> CastResponse {
        CastResponse {
            g_cast_enabled,
        }
    }
}

