/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePasswordDto {
    /// Invalidate all other sessions
    #[serde(rename = "invalidateSessions", skip_serializing_if = "Option::is_none")]
    pub invalidate_sessions: Option<bool>,
    /// New password (min 8 characters)
    #[serde(rename = "newPassword")]
    pub new_password: String,
    /// Current password
    #[serde(rename = "password")]
    pub password: String,
}

impl ChangePasswordDto {
    pub fn new(new_password: String, password: String) -> ChangePasswordDto {
        ChangePasswordDto {
            invalidate_sessions: None,
            new_password,
            password,
        }
    }
}

