/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContributorCountResponseDto {
    /// Number of assets contributed
    #[serde(rename = "assetCount")]
    pub asset_count: i32,
    /// User ID
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl ContributorCountResponseDto {
    pub fn new(asset_count: i32, user_id: String) -> ContributorCountResponseDto {
        ContributorCountResponseDto {
            asset_count,
            user_id,
        }
    }
}

