/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseBackupDeleteDto {
    /// Backup filenames to delete
    #[serde(rename = "backups")]
    pub backups: Vec<String>,
}

impl DatabaseBackupDeleteDto {
    pub fn new(backups: Vec<String>) -> DatabaseBackupDeleteDto {
        DatabaseBackupDeleteDto {
            backups,
        }
    }
}

