/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadUpdate {
    /// Maximum archive size in bytes
    #[serde(rename = "archiveSize", skip_serializing_if = "Option::is_none")]
    pub archive_size: Option<i32>,
    /// Whether to include embedded videos in downloads
    #[serde(rename = "includeEmbeddedVideos", skip_serializing_if = "Option::is_none")]
    pub include_embedded_videos: Option<bool>,
}

impl DownloadUpdate {
    pub fn new() -> DownloadUpdate {
        DownloadUpdate {
            archive_size: None,
            include_embedded_videos: None,
        }
    }
}

