/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DuplicateResolveGroupDto {
    #[serde(rename = "duplicateId")]
    pub duplicate_id: uuid::Uuid,
    /// Asset IDs to keep
    #[serde(rename = "keepAssetIds")]
    pub keep_asset_ids: Vec<uuid::Uuid>,
    /// Asset IDs to trash or delete
    #[serde(rename = "trashAssetIds")]
    pub trash_asset_ids: Vec<uuid::Uuid>,
}

impl DuplicateResolveGroupDto {
    pub fn new(duplicate_id: uuid::Uuid, keep_asset_ids: Vec<uuid::Uuid>, trash_asset_ids: Vec<uuid::Uuid>) -> DuplicateResolveGroupDto {
        DuplicateResolveGroupDto {
            duplicate_id,
            keep_asset_ids,
            trash_asset_ids,
        }
    }
}

