/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExifResponseDto : EXIF response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExifResponseDto {
    /// City name
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<String>>,
    /// Country name
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<String>>,
    /// Original date/time
    #[serde(rename = "dateTimeOriginal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_time_original: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Image description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Image height in pixels
    #[serde(rename = "exifImageHeight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exif_image_height: Option<Option<i32>>,
    /// Image width in pixels
    #[serde(rename = "exifImageWidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exif_image_width: Option<Option<i32>>,
    /// Exposure time
    #[serde(rename = "exposureTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exposure_time: Option<Option<String>>,
    /// F-number (aperture)
    #[serde(rename = "fNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub f_number: Option<Option<f64>>,
    /// File size in bytes
    #[serde(rename = "fileSizeInByte", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size_in_byte: Option<Option<i32>>,
    /// Focal length in mm
    #[serde(rename = "focalLength", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub focal_length: Option<Option<f64>>,
    /// ISO sensitivity
    #[serde(rename = "iso", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso: Option<Option<i32>>,
    /// GPS latitude
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<f64>>,
    /// Lens model
    #[serde(rename = "lensModel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lens_model: Option<Option<String>>,
    /// GPS longitude
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<f64>>,
    /// Camera make
    #[serde(rename = "make", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub make: Option<Option<String>>,
    /// Camera model
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    /// Modification date/time
    #[serde(rename = "modifyDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub modify_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Image orientation
    #[serde(rename = "orientation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<Option<String>>,
    /// Projection type
    #[serde(rename = "projectionType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub projection_type: Option<Option<String>>,
    /// Rating
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<i32>>,
    /// State/province name
    #[serde(rename = "state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state: Option<Option<String>>,
    /// Time zone
    #[serde(rename = "timeZone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Option<String>>,
}

impl ExifResponseDto {
    /// EXIF response
    pub fn new() -> ExifResponseDto {
        ExifResponseDto {
            city: None,
            country: None,
            date_time_original: None,
            description: None,
            exif_image_height: None,
            exif_image_width: None,
            exposure_time: None,
            f_number: None,
            file_size_in_byte: None,
            focal_length: None,
            iso: None,
            latitude: None,
            lens_model: None,
            longitude: None,
            make: None,
            model: None,
            modify_date: None,
            orientation: None,
            projection_type: None,
            rating: None,
            state: None,
            time_zone: None,
        }
    }
}

