/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobName : Job name
/// Job name
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobName {
    #[serde(rename = "AssetDelete")]
    AssetDelete,
    #[serde(rename = "AssetDeleteCheck")]
    AssetDeleteCheck,
    #[serde(rename = "AssetDetectFacesQueueAll")]
    AssetDetectFacesQueueAll,
    #[serde(rename = "AssetDetectFaces")]
    AssetDetectFaces,
    #[serde(rename = "AssetDetectDuplicatesQueueAll")]
    AssetDetectDuplicatesQueueAll,
    #[serde(rename = "AssetDetectDuplicates")]
    AssetDetectDuplicates,
    #[serde(rename = "AssetEditThumbnailGeneration")]
    AssetEditThumbnailGeneration,
    #[serde(rename = "AssetEncodeVideoQueueAll")]
    AssetEncodeVideoQueueAll,
    #[serde(rename = "AssetEncodeVideo")]
    AssetEncodeVideo,
    #[serde(rename = "AssetEmptyTrash")]
    AssetEmptyTrash,
    #[serde(rename = "AssetExtractMetadataQueueAll")]
    AssetExtractMetadataQueueAll,
    #[serde(rename = "AssetExtractMetadata")]
    AssetExtractMetadata,
    #[serde(rename = "AssetFileMigration")]
    AssetFileMigration,
    #[serde(rename = "AssetGenerateThumbnailsQueueAll")]
    AssetGenerateThumbnailsQueueAll,
    #[serde(rename = "AssetGenerateThumbnails")]
    AssetGenerateThumbnails,
    #[serde(rename = "AuditTableCleanup")]
    AuditTableCleanup,
    #[serde(rename = "DatabaseBackup")]
    DatabaseBackup,
    #[serde(rename = "FacialRecognitionQueueAll")]
    FacialRecognitionQueueAll,
    #[serde(rename = "FacialRecognition")]
    FacialRecognition,
    #[serde(rename = "FileDelete")]
    FileDelete,
    #[serde(rename = "FileMigrationQueueAll")]
    FileMigrationQueueAll,
    #[serde(rename = "LibraryDeleteCheck")]
    LibraryDeleteCheck,
    #[serde(rename = "LibraryDelete")]
    LibraryDelete,
    #[serde(rename = "LibraryRemoveAsset")]
    LibraryRemoveAsset,
    #[serde(rename = "LibraryScanAssetsQueueAll")]
    LibraryScanAssetsQueueAll,
    #[serde(rename = "LibrarySyncAssets")]
    LibrarySyncAssets,
    #[serde(rename = "LibrarySyncFilesQueueAll")]
    LibrarySyncFilesQueueAll,
    #[serde(rename = "LibrarySyncFiles")]
    LibrarySyncFiles,
    #[serde(rename = "LibraryScanQueueAll")]
    LibraryScanQueueAll,
    #[serde(rename = "MemoryCleanup")]
    MemoryCleanup,
    #[serde(rename = "MemoryGenerate")]
    MemoryGenerate,
    #[serde(rename = "NotificationsCleanup")]
    NotificationsCleanup,
    #[serde(rename = "NotifyUserSignup")]
    NotifyUserSignup,
    #[serde(rename = "NotifyAlbumInvite")]
    NotifyAlbumInvite,
    #[serde(rename = "NotifyAlbumUpdate")]
    NotifyAlbumUpdate,
    #[serde(rename = "UserDelete")]
    UserDelete,
    #[serde(rename = "UserDeleteCheck")]
    UserDeleteCheck,
    #[serde(rename = "UserSyncUsage")]
    UserSyncUsage,
    #[serde(rename = "PersonCleanup")]
    PersonCleanup,
    #[serde(rename = "PersonFileMigration")]
    PersonFileMigration,
    #[serde(rename = "PersonGenerateThumbnail")]
    PersonGenerateThumbnail,
    #[serde(rename = "SessionCleanup")]
    SessionCleanup,
    #[serde(rename = "SendMail")]
    SendMail,
    #[serde(rename = "SidecarQueueAll")]
    SidecarQueueAll,
    #[serde(rename = "SidecarCheck")]
    SidecarCheck,
    #[serde(rename = "SidecarWrite")]
    SidecarWrite,
    #[serde(rename = "SmartSearchQueueAll")]
    SmartSearchQueueAll,
    #[serde(rename = "SmartSearch")]
    SmartSearch,
    #[serde(rename = "StorageTemplateMigration")]
    StorageTemplateMigration,
    #[serde(rename = "StorageTemplateMigrationSingle")]
    StorageTemplateMigrationSingle,
    #[serde(rename = "TagCleanup")]
    TagCleanup,
    #[serde(rename = "VersionCheck")]
    VersionCheck,
    #[serde(rename = "OcrQueueAll")]
    OcrQueueAll,
    #[serde(rename = "Ocr")]
    Ocr,
    #[serde(rename = "WorkflowAssetCreate")]
    WorkflowAssetCreate,

}

impl std::fmt::Display for JobName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AssetDelete => write!(f, "AssetDelete"),
            Self::AssetDeleteCheck => write!(f, "AssetDeleteCheck"),
            Self::AssetDetectFacesQueueAll => write!(f, "AssetDetectFacesQueueAll"),
            Self::AssetDetectFaces => write!(f, "AssetDetectFaces"),
            Self::AssetDetectDuplicatesQueueAll => write!(f, "AssetDetectDuplicatesQueueAll"),
            Self::AssetDetectDuplicates => write!(f, "AssetDetectDuplicates"),
            Self::AssetEditThumbnailGeneration => write!(f, "AssetEditThumbnailGeneration"),
            Self::AssetEncodeVideoQueueAll => write!(f, "AssetEncodeVideoQueueAll"),
            Self::AssetEncodeVideo => write!(f, "AssetEncodeVideo"),
            Self::AssetEmptyTrash => write!(f, "AssetEmptyTrash"),
            Self::AssetExtractMetadataQueueAll => write!(f, "AssetExtractMetadataQueueAll"),
            Self::AssetExtractMetadata => write!(f, "AssetExtractMetadata"),
            Self::AssetFileMigration => write!(f, "AssetFileMigration"),
            Self::AssetGenerateThumbnailsQueueAll => write!(f, "AssetGenerateThumbnailsQueueAll"),
            Self::AssetGenerateThumbnails => write!(f, "AssetGenerateThumbnails"),
            Self::AuditTableCleanup => write!(f, "AuditTableCleanup"),
            Self::DatabaseBackup => write!(f, "DatabaseBackup"),
            Self::FacialRecognitionQueueAll => write!(f, "FacialRecognitionQueueAll"),
            Self::FacialRecognition => write!(f, "FacialRecognition"),
            Self::FileDelete => write!(f, "FileDelete"),
            Self::FileMigrationQueueAll => write!(f, "FileMigrationQueueAll"),
            Self::LibraryDeleteCheck => write!(f, "LibraryDeleteCheck"),
            Self::LibraryDelete => write!(f, "LibraryDelete"),
            Self::LibraryRemoveAsset => write!(f, "LibraryRemoveAsset"),
            Self::LibraryScanAssetsQueueAll => write!(f, "LibraryScanAssetsQueueAll"),
            Self::LibrarySyncAssets => write!(f, "LibrarySyncAssets"),
            Self::LibrarySyncFilesQueueAll => write!(f, "LibrarySyncFilesQueueAll"),
            Self::LibrarySyncFiles => write!(f, "LibrarySyncFiles"),
            Self::LibraryScanQueueAll => write!(f, "LibraryScanQueueAll"),
            Self::MemoryCleanup => write!(f, "MemoryCleanup"),
            Self::MemoryGenerate => write!(f, "MemoryGenerate"),
            Self::NotificationsCleanup => write!(f, "NotificationsCleanup"),
            Self::NotifyUserSignup => write!(f, "NotifyUserSignup"),
            Self::NotifyAlbumInvite => write!(f, "NotifyAlbumInvite"),
            Self::NotifyAlbumUpdate => write!(f, "NotifyAlbumUpdate"),
            Self::UserDelete => write!(f, "UserDelete"),
            Self::UserDeleteCheck => write!(f, "UserDeleteCheck"),
            Self::UserSyncUsage => write!(f, "UserSyncUsage"),
            Self::PersonCleanup => write!(f, "PersonCleanup"),
            Self::PersonFileMigration => write!(f, "PersonFileMigration"),
            Self::PersonGenerateThumbnail => write!(f, "PersonGenerateThumbnail"),
            Self::SessionCleanup => write!(f, "SessionCleanup"),
            Self::SendMail => write!(f, "SendMail"),
            Self::SidecarQueueAll => write!(f, "SidecarQueueAll"),
            Self::SidecarCheck => write!(f, "SidecarCheck"),
            Self::SidecarWrite => write!(f, "SidecarWrite"),
            Self::SmartSearchQueueAll => write!(f, "SmartSearchQueueAll"),
            Self::SmartSearch => write!(f, "SmartSearch"),
            Self::StorageTemplateMigration => write!(f, "StorageTemplateMigration"),
            Self::StorageTemplateMigrationSingle => write!(f, "StorageTemplateMigrationSingle"),
            Self::TagCleanup => write!(f, "TagCleanup"),
            Self::VersionCheck => write!(f, "VersionCheck"),
            Self::OcrQueueAll => write!(f, "OcrQueueAll"),
            Self::Ocr => write!(f, "Ocr"),
            Self::WorkflowAssetCreate => write!(f, "WorkflowAssetCreate"),
        }
    }
}

impl Default for JobName {
    fn default() -> JobName {
        Self::AssetDelete
    }
}

