/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginResponseDto {
    /// Access token
    #[serde(rename = "accessToken")]
    pub access_token: String,
    /// Is admin user
    #[serde(rename = "isAdmin")]
    pub is_admin: bool,
    /// Is onboarded
    #[serde(rename = "isOnboarded")]
    pub is_onboarded: bool,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// Profile image path
    #[serde(rename = "profileImagePath")]
    pub profile_image_path: String,
    /// Should change password
    #[serde(rename = "shouldChangePassword")]
    pub should_change_password: bool,
    /// User email
    #[serde(rename = "userEmail")]
    pub user_email: String,
    /// User ID
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl LoginResponseDto {
    pub fn new(access_token: String, is_admin: bool, is_onboarded: bool, name: String, profile_image_path: String, should_change_password: bool, user_email: String, user_id: String) -> LoginResponseDto {
        LoginResponseDto {
            access_token,
            is_admin,
            is_onboarded,
            name,
            profile_image_path,
            should_change_password,
            user_email,
            user_id,
        }
    }
}

