/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MachineLearningAvailabilityChecksDto {
    /// Enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "interval")]
    pub interval: i32,
    #[serde(rename = "timeout")]
    pub timeout: i32,
}

impl MachineLearningAvailabilityChecksDto {
    pub fn new(enabled: bool, interval: i32, timeout: i32) -> MachineLearningAvailabilityChecksDto {
        MachineLearningAvailabilityChecksDto {
            enabled,
            interval,
            timeout,
        }
    }
}

