/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaintenanceDetectInstallResponseDto {
    #[serde(rename = "storage")]
    pub storage: Vec<models::MaintenanceDetectInstallStorageFolderDto>,
}

impl MaintenanceDetectInstallResponseDto {
    pub fn new(storage: Vec<models::MaintenanceDetectInstallStorageFolderDto>) -> MaintenanceDetectInstallResponseDto {
        MaintenanceDetectInstallResponseDto {
            storage,
        }
    }
}

