/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MemoryType : Memory type
/// Memory type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MemoryType {
    #[serde(rename = "on_this_day")]
    OnThisDay,

}

impl std::fmt::Display for MemoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OnThisDay => write!(f, "on_this_day"),
        }
    }
}

impl Default for MemoryType {
    fn default() -> MemoryType {
        Self::OnThisDay
    }
}

