/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemoryResponseDto {
    #[serde(rename = "assets")]
    pub assets: Vec<models::AssetResponseDto>,
    /// Creation date
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "data")]
    pub data: Box<models::OnThisDayDto>,
    /// Deletion date
    #[serde(rename = "deletedAt", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date when memory should be hidden
    #[serde(rename = "hideAt", skip_serializing_if = "Option::is_none")]
    pub hide_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Memory ID
    #[serde(rename = "id")]
    pub id: String,
    /// Is memory saved
    #[serde(rename = "isSaved")]
    pub is_saved: bool,
    /// Memory date
    #[serde(rename = "memoryAt")]
    pub memory_at: chrono::DateTime<chrono::FixedOffset>,
    /// Owner user ID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// Date when memory was seen
    #[serde(rename = "seenAt", skip_serializing_if = "Option::is_none")]
    pub seen_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date when memory should be shown
    #[serde(rename = "showAt", skip_serializing_if = "Option::is_none")]
    pub show_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "type")]
    pub r#type: models::MemoryType,
    /// Last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl MemoryResponseDto {
    pub fn new(assets: Vec<models::AssetResponseDto>, created_at: chrono::DateTime<chrono::FixedOffset>, data: models::OnThisDayDto, id: String, is_saved: bool, memory_at: chrono::DateTime<chrono::FixedOffset>, owner_id: String, r#type: models::MemoryType, updated_at: chrono::DateTime<chrono::FixedOffset>) -> MemoryResponseDto {
        MemoryResponseDto {
            assets,
            created_at,
            data: Box::new(data),
            deleted_at: None,
            hide_at: None,
            id,
            is_saved,
            memory_at,
            owner_id,
            seen_at: None,
            show_at: None,
            r#type,
            updated_at,
        }
    }
}

