/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MirrorParameters {
    #[serde(rename = "axis")]
    pub axis: models::MirrorAxis,
}

impl MirrorParameters {
    pub fn new(axis: models::MirrorAxis) -> MirrorParameters {
        MirrorParameters {
            axis,
        }
    }
}

