/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationType : Notification type
/// Notification type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationType {
    #[serde(rename = "JobFailed")]
    JobFailed,
    #[serde(rename = "BackupFailed")]
    BackupFailed,
    #[serde(rename = "SystemMessage")]
    SystemMessage,
    #[serde(rename = "AlbumInvite")]
    AlbumInvite,
    #[serde(rename = "AlbumUpdate")]
    AlbumUpdate,
    #[serde(rename = "Custom")]
    Custom,

}

impl std::fmt::Display for NotificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JobFailed => write!(f, "JobFailed"),
            Self::BackupFailed => write!(f, "BackupFailed"),
            Self::SystemMessage => write!(f, "SystemMessage"),
            Self::AlbumInvite => write!(f, "AlbumInvite"),
            Self::AlbumUpdate => write!(f, "AlbumUpdate"),
            Self::Custom => write!(f, "Custom"),
        }
    }
}

impl Default for NotificationType {
    fn default() -> NotificationType {
        Self::JobFailed
    }
}

