/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationDeleteAllDto {
    /// Notification IDs to delete
    #[serde(rename = "ids")]
    pub ids: Vec<uuid::Uuid>,
}

impl NotificationDeleteAllDto {
    pub fn new(ids: Vec<uuid::Uuid>) -> NotificationDeleteAllDto {
        NotificationDeleteAllDto {
            ids,
        }
    }
}

