/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationDto {
    /// Creation date
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Additional notification data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Notification description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Notification ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "level")]
    pub level: models::NotificationLevel,
    /// Date when notification was read
    #[serde(rename = "readAt", skip_serializing_if = "Option::is_none")]
    pub read_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Notification title
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: models::NotificationType,
}

impl NotificationDto {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, level: models::NotificationLevel, title: String, r#type: models::NotificationType) -> NotificationDto {
        NotificationDto {
            created_at,
            data: None,
            description: None,
            id,
            level,
            read_at: None,
            title,
            r#type,
        }
    }
}

