/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthConfigDto {
    /// OAuth code challenge (PKCE)
    #[serde(rename = "codeChallenge", skip_serializing_if = "Option::is_none")]
    pub code_challenge: Option<String>,
    /// OAuth redirect URI
    #[serde(rename = "redirectUri")]
    pub redirect_uri: String,
    /// OAuth state parameter
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

impl OAuthConfigDto {
    pub fn new(redirect_uri: String) -> OAuthConfigDto {
        OAuthConfigDto {
            code_challenge: None,
            redirect_uri,
            state: None,
        }
    }
}

