/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthAuthorizeResponseDto {
    /// OAuth authorization URL
    #[serde(rename = "url")]
    pub url: String,
}

impl OAuthAuthorizeResponseDto {
    pub fn new(url: String) -> OAuthAuthorizeResponseDto {
        OAuthAuthorizeResponseDto {
            url,
        }
    }
}

