/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthCallbackDto {
    /// OAuth code verifier (PKCE)
    #[serde(rename = "codeVerifier", skip_serializing_if = "Option::is_none")]
    pub code_verifier: Option<String>,
    /// OAuth state parameter
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// OAuth callback URL
    #[serde(rename = "url")]
    pub url: String,
}

impl OAuthCallbackDto {
    pub fn new(url: String) -> OAuthCallbackDto {
        OAuthCallbackDto {
            code_verifier: None,
            state: None,
            url,
        }
    }
}

