/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnboardingResponseDto {
    /// Is user onboarded
    #[serde(rename = "isOnboarded")]
    pub is_onboarded: bool,
}

impl OnboardingResponseDto {
    pub fn new(is_onboarded: bool) -> OnboardingResponseDto {
        OnboardingResponseDto {
            is_onboarded,
        }
    }
}

