/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerResponseDto : Partner response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerResponseDto {
    #[serde(rename = "avatarColor")]
    pub avatar_color: models::UserAvatarColor,
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// User ID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Show in timeline
    #[serde(rename = "inTimeline", skip_serializing_if = "Option::is_none")]
    pub in_timeline: Option<bool>,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// Profile change date
    #[serde(rename = "profileChangedAt")]
    pub profile_changed_at: chrono::DateTime<chrono::FixedOffset>,
    /// Profile image path
    #[serde(rename = "profileImagePath")]
    pub profile_image_path: String,
}

impl PartnerResponseDto {
    /// Partner response
    pub fn new(avatar_color: models::UserAvatarColor, email: String, id: uuid::Uuid, name: String, profile_changed_at: chrono::DateTime<chrono::FixedOffset>, profile_image_path: String) -> PartnerResponseDto {
        PartnerResponseDto {
            avatar_color,
            email,
            id,
            in_timeline: None,
            name,
            profile_changed_at,
            profile_image_path,
        }
    }
}

