/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerDirection : Partner direction
/// Partner direction
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PartnerDirection {
    #[serde(rename = "shared-by")]
    SharedBy,
    #[serde(rename = "shared-with")]
    SharedWith,

}

impl std::fmt::Display for PartnerDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SharedBy => write!(f, "shared-by"),
            Self::SharedWith => write!(f, "shared-with"),
        }
    }
}

impl Default for PartnerDirection {
    fn default() -> PartnerDirection {
        Self::SharedBy
    }
}

