/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonUpdateDto {
    /// Person date of birth
    #[serde(rename = "birthDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<Option<chrono::NaiveDate>>,
    /// Person color (hex)
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    /// Asset ID used for feature face thumbnail
    #[serde(rename = "featureFaceAssetId", skip_serializing_if = "Option::is_none")]
    pub feature_face_asset_id: Option<uuid::Uuid>,
    /// Mark as favorite
    #[serde(rename = "isFavorite", skip_serializing_if = "Option::is_none")]
    pub is_favorite: Option<bool>,
    /// Person visibility (hidden)
    #[serde(rename = "isHidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
    /// Person name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PersonUpdateDto {
    pub fn new() -> PersonUpdateDto {
        PersonUpdateDto {
            birth_date: None,
            color: None,
            feature_face_asset_id: None,
            is_favorite: None,
            is_hidden: None,
            name: None,
        }
    }
}

