/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinCodeResetDto {
    /// User password (required if PIN code is not provided)
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// New PIN code (4-6 digits)
    #[serde(rename = "pinCode", skip_serializing_if = "Option::is_none")]
    pub pin_code: Option<String>,
}

impl PinCodeResetDto {
    pub fn new() -> PinCodeResetDto {
        PinCodeResetDto {
            password: None,
            pin_code: None,
        }
    }
}

