/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinCodeSetupDto {
    /// PIN code (4-6 digits)
    #[serde(rename = "pinCode")]
    pub pin_code: String,
}

impl PinCodeSetupDto {
    pub fn new(pin_code: String) -> PinCodeSetupDto {
        PinCodeSetupDto {
            pin_code,
        }
    }
}

