/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlacesResponseDto {
    /// Administrative level 1 name (state/province)
    #[serde(rename = "admin1name", skip_serializing_if = "Option::is_none")]
    pub admin1name: Option<String>,
    /// Administrative level 2 name (county/district)
    #[serde(rename = "admin2name", skip_serializing_if = "Option::is_none")]
    pub admin2name: Option<String>,
    /// Latitude coordinate
    #[serde(rename = "latitude")]
    pub latitude: f64,
    /// Longitude coordinate
    #[serde(rename = "longitude")]
    pub longitude: f64,
    /// Place name
    #[serde(rename = "name")]
    pub name: String,
}

impl PlacesResponseDto {
    pub fn new(latitude: f64, longitude: f64, name: String) -> PlacesResponseDto {
        PlacesResponseDto {
            admin1name: None,
            admin2name: None,
            latitude,
            longitude,
            name,
        }
    }
}

