/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseResponse {
    /// Date until which to hide buy button
    #[serde(rename = "hideBuyButtonUntil")]
    pub hide_buy_button_until: String,
    /// Whether to show support badge
    #[serde(rename = "showSupportBadge")]
    pub show_support_badge: bool,
}

impl PurchaseResponse {
    pub fn new(hide_buy_button_until: String, show_support_badge: bool) -> PurchaseResponse {
        PurchaseResponse {
            hide_buy_button_until,
            show_support_badge,
        }
    }
}

