/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueuesResponseLegacyDto {
    #[serde(rename = "backgroundTask")]
    pub background_task: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "backupDatabase")]
    pub backup_database: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "duplicateDetection")]
    pub duplicate_detection: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "editor")]
    pub editor: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "faceDetection")]
    pub face_detection: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "facialRecognition")]
    pub facial_recognition: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "library")]
    pub library: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "metadataExtraction")]
    pub metadata_extraction: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "migration")]
    pub migration: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "notifications")]
    pub notifications: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "ocr")]
    pub ocr: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "search")]
    pub search: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "sidecar")]
    pub sidecar: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "smartSearch")]
    pub smart_search: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "storageTemplateMigration")]
    pub storage_template_migration: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "thumbnailGeneration")]
    pub thumbnail_generation: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "videoConversion")]
    pub video_conversion: Box<models::QueueResponseLegacyDto>,
    #[serde(rename = "workflow")]
    pub workflow: Box<models::QueueResponseLegacyDto>,
}

impl QueuesResponseLegacyDto {
    pub fn new(background_task: models::QueueResponseLegacyDto, backup_database: models::QueueResponseLegacyDto, duplicate_detection: models::QueueResponseLegacyDto, editor: models::QueueResponseLegacyDto, face_detection: models::QueueResponseLegacyDto, facial_recognition: models::QueueResponseLegacyDto, library: models::QueueResponseLegacyDto, metadata_extraction: models::QueueResponseLegacyDto, migration: models::QueueResponseLegacyDto, notifications: models::QueueResponseLegacyDto, ocr: models::QueueResponseLegacyDto, search: models::QueueResponseLegacyDto, sidecar: models::QueueResponseLegacyDto, smart_search: models::QueueResponseLegacyDto, storage_template_migration: models::QueueResponseLegacyDto, thumbnail_generation: models::QueueResponseLegacyDto, video_conversion: models::QueueResponseLegacyDto, workflow: models::QueueResponseLegacyDto) -> QueuesResponseLegacyDto {
        QueuesResponseLegacyDto {
            background_task: Box::new(background_task),
            backup_database: Box::new(backup_database),
            duplicate_detection: Box::new(duplicate_detection),
            editor: Box::new(editor),
            face_detection: Box::new(face_detection),
            facial_recognition: Box::new(facial_recognition),
            library: Box::new(library),
            metadata_extraction: Box::new(metadata_extraction),
            migration: Box::new(migration),
            notifications: Box::new(notifications),
            ocr: Box::new(ocr),
            search: Box::new(search),
            sidecar: Box::new(sidecar),
            smart_search: Box::new(smart_search),
            storage_template_migration: Box::new(storage_template_migration),
            thumbnail_generation: Box::new(thumbnail_generation),
            video_conversion: Box::new(video_conversion),
            workflow: Box::new(workflow),
        }
    }
}

