/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateParameters {
    /// Rotation angle in degrees
    #[serde(rename = "angle")]
    pub angle: f64,
}

impl RotateParameters {
    pub fn new(angle: f64) -> RotateParameters {
        RotateParameters {
            angle,
        }
    }
}

