/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFacetCountResponseDto {
    /// Number of assets with this facet value
    #[serde(rename = "count")]
    pub count: i32,
    /// Facet value
    #[serde(rename = "value")]
    pub value: String,
}

impl SearchFacetCountResponseDto {
    pub fn new(count: i32, value: String) -> SearchFacetCountResponseDto {
        SearchFacetCountResponseDto {
            count,
            value,
        }
    }
}

