/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerApkLinksDto {
    /// APK download link for ARM64 v8a architecture
    #[serde(rename = "arm64v8a")]
    pub arm64v8a: String,
    /// APK download link for ARM EABI v7a architecture
    #[serde(rename = "armeabiv7a")]
    pub armeabiv7a: String,
    /// APK download link for universal architecture
    #[serde(rename = "universal")]
    pub universal: String,
    /// APK download link for x86_64 architecture
    #[serde(rename = "x86_64")]
    pub x86_64: String,
}

impl ServerApkLinksDto {
    pub fn new(arm64v8a: String, armeabiv7a: String, universal: String, x86_64: String) -> ServerApkLinksDto {
        ServerApkLinksDto {
            arm64v8a,
            armeabiv7a,
            universal,
            x86_64,
        }
    }
}

