/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerVersionHistoryResponseDto {
    /// When this version was first seen
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Version history entry ID
    #[serde(rename = "id")]
    pub id: String,
    /// Version string
    #[serde(rename = "version")]
    pub version: String,
}

impl ServerVersionHistoryResponseDto {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, version: String) -> ServerVersionHistoryResponseDto {
        ServerVersionHistoryResponseDto {
            created_at,
            id,
            version,
        }
    }
}

