/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpDto {
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// User password
    #[serde(rename = "password")]
    pub password: String,
}

impl SignUpDto {
    pub fn new(email: String, name: String, password: String) -> SignUpDto {
        SignUpDto {
            email,
            name,
            password,
        }
    }
}

