/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmartSearchDto {
    /// Filter by album IDs
    #[serde(rename = "albumIds", skip_serializing_if = "Option::is_none")]
    pub album_ids: Option<Vec<uuid::Uuid>>,
    /// Filter by city name
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<String>>,
    /// Filter by country name
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<String>>,
    /// Filter by creation date (after)
    #[serde(rename = "createdAfter", skip_serializing_if = "Option::is_none")]
    pub created_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by creation date (before)
    #[serde(rename = "createdBefore", skip_serializing_if = "Option::is_none")]
    pub created_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by encoded status
    #[serde(rename = "isEncoded", skip_serializing_if = "Option::is_none")]
    pub is_encoded: Option<bool>,
    /// Filter by favorite status
    #[serde(rename = "isFavorite", skip_serializing_if = "Option::is_none")]
    pub is_favorite: Option<bool>,
    /// Filter by motion photo status
    #[serde(rename = "isMotion", skip_serializing_if = "Option::is_none")]
    pub is_motion: Option<bool>,
    /// Filter assets not in any album
    #[serde(rename = "isNotInAlbum", skip_serializing_if = "Option::is_none")]
    pub is_not_in_album: Option<bool>,
    /// Filter by offline status
    #[serde(rename = "isOffline", skip_serializing_if = "Option::is_none")]
    pub is_offline: Option<bool>,
    /// Search language code
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Filter by lens model
    #[serde(rename = "lensModel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lens_model: Option<Option<String>>,
    /// Library ID to filter by
    #[serde(rename = "libraryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub library_id: Option<Option<uuid::Uuid>>,
    /// Filter by camera make
    #[serde(rename = "make", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub make: Option<Option<String>>,
    /// Filter by camera model
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    /// Filter by OCR text content
    #[serde(rename = "ocr", skip_serializing_if = "Option::is_none")]
    pub ocr: Option<String>,
    /// Page number
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// Filter by person IDs
    #[serde(rename = "personIds", skip_serializing_if = "Option::is_none")]
    pub person_ids: Option<Vec<uuid::Uuid>>,
    /// Natural language search query
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Asset ID to use as search reference
    #[serde(rename = "queryAssetId", skip_serializing_if = "Option::is_none")]
    pub query_asset_id: Option<uuid::Uuid>,
    /// Filter by rating [1-5], or null for unrated
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<i32>>,
    /// Number of results to return
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// Filter by state/province name
    #[serde(rename = "state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state: Option<Option<String>>,
    /// Filter by tag IDs
    #[serde(rename = "tagIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// Filter by taken date (after)
    #[serde(rename = "takenAfter", skip_serializing_if = "Option::is_none")]
    pub taken_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by taken date (before)
    #[serde(rename = "takenBefore", skip_serializing_if = "Option::is_none")]
    pub taken_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by trash date (after)
    #[serde(rename = "trashedAfter", skip_serializing_if = "Option::is_none")]
    pub trashed_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by trash date (before)
    #[serde(rename = "trashedBefore", skip_serializing_if = "Option::is_none")]
    pub trashed_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::AssetTypeEnum>,
    /// Filter by update date (after)
    #[serde(rename = "updatedAfter", skip_serializing_if = "Option::is_none")]
    pub updated_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by update date (before)
    #[serde(rename = "updatedBefore", skip_serializing_if = "Option::is_none")]
    pub updated_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::AssetVisibility>,
    /// Include deleted assets
    #[serde(rename = "withDeleted", skip_serializing_if = "Option::is_none")]
    pub with_deleted: Option<bool>,
    /// Include EXIF data in response
    #[serde(rename = "withExif", skip_serializing_if = "Option::is_none")]
    pub with_exif: Option<bool>,
}

impl SmartSearchDto {
    pub fn new() -> SmartSearchDto {
        SmartSearchDto {
            album_ids: None,
            city: None,
            country: None,
            created_after: None,
            created_before: None,
            is_encoded: None,
            is_favorite: None,
            is_motion: None,
            is_not_in_album: None,
            is_offline: None,
            language: None,
            lens_model: None,
            library_id: None,
            make: None,
            model: None,
            ocr: None,
            page: None,
            person_ids: None,
            query: None,
            query_asset_id: None,
            rating: None,
            size: None,
            state: None,
            tag_ids: None,
            taken_after: None,
            taken_before: None,
            trashed_after: None,
            trashed_before: None,
            r#type: None,
            updated_after: None,
            updated_before: None,
            visibility: None,
            with_deleted: None,
            with_exif: None,
        }
    }
}

