/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SourceType : Face detection source type
/// Face detection source type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "machine-learning")]
    MachineLearning,
    #[serde(rename = "exif")]
    Exif,
    #[serde(rename = "manual")]
    Manual,

}

impl std::fmt::Display for SourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MachineLearning => write!(f, "machine-learning"),
            Self::Exif => write!(f, "exif"),
            Self::Manual => write!(f, "manual"),
        }
    }
}

impl Default for SourceType {
    fn default() -> SourceType {
        Self::MachineLearning
    }
}

