/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StackResponseDto : Stack response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StackResponseDto {
    #[serde(rename = "assets")]
    pub assets: Vec<models::AssetResponseDto>,
    /// Stack ID
    #[serde(rename = "id")]
    pub id: String,
    /// Primary asset ID
    #[serde(rename = "primaryAssetId")]
    pub primary_asset_id: String,
}

impl StackResponseDto {
    /// Stack response
    pub fn new(assets: Vec<models::AssetResponseDto>, id: String, primary_asset_id: String) -> StackResponseDto {
        StackResponseDto {
            assets,
            id,
            primary_asset_id,
        }
    }
}

