/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncUserMetadataDeleteV1 {
    #[serde(rename = "key")]
    pub key: models::UserMetadataKey,
    /// User ID
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl SyncUserMetadataDeleteV1 {
    pub fn new(key: models::UserMetadataKey, user_id: String) -> SyncUserMetadataDeleteV1 {
        SyncUserMetadataDeleteV1 {
            key,
            user_id,
        }
    }
}

