/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAckDeleteDto {
    /// Sync entity types to delete acks for
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<models::SyncEntityType>>,
}

impl SyncAckDeleteDto {
    pub fn new() -> SyncAckDeleteDto {
        SyncAckDeleteDto {
            types: None,
        }
    }
}

