/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncPersonV1 {
    /// Birth date
    #[serde(rename = "birthDate", deserialize_with = "Option::deserialize")]
    pub birth_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Color
    #[serde(rename = "color", deserialize_with = "Option::deserialize")]
    pub color: Option<String>,
    /// Created at
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Face asset ID
    #[serde(rename = "faceAssetId", deserialize_with = "Option::deserialize")]
    pub face_asset_id: Option<String>,
    /// Person ID
    #[serde(rename = "id")]
    pub id: String,
    /// Is favorite
    #[serde(rename = "isFavorite")]
    pub is_favorite: bool,
    /// Is hidden
    #[serde(rename = "isHidden")]
    pub is_hidden: bool,
    /// Person name
    #[serde(rename = "name")]
    pub name: String,
    /// Owner ID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// Updated at
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SyncPersonV1 {
    pub fn new(birth_date: Option<chrono::DateTime<chrono::FixedOffset>>, color: Option<String>, created_at: chrono::DateTime<chrono::FixedOffset>, face_asset_id: Option<String>, id: String, is_favorite: bool, is_hidden: bool, name: String, owner_id: String, updated_at: chrono::DateTime<chrono::FixedOffset>) -> SyncPersonV1 {
        SyncPersonV1 {
            birth_date,
            color,
            created_at,
            face_asset_id,
            id,
            is_favorite,
            is_hidden,
            name,
            owner_id,
            updated_at,
        }
    }
}

