/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncPersonDeleteV1 {
    /// Person ID
    #[serde(rename = "personId")]
    pub person_id: String,
}

impl SyncPersonDeleteV1 {
    pub fn new(person_id: String) -> SyncPersonDeleteV1 {
        SyncPersonDeleteV1 {
            person_id,
        }
    }
}

