/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAlbumUserDeleteV1 {
    /// Album ID
    #[serde(rename = "albumId")]
    pub album_id: String,
    /// User ID
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl SyncAlbumUserDeleteV1 {
    pub fn new(album_id: String, user_id: String) -> SyncAlbumUserDeleteV1 {
        SyncAlbumUserDeleteV1 {
            album_id,
            user_id,
        }
    }
}

