/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAckDto {
    /// Acknowledgment ID
    #[serde(rename = "ack")]
    pub ack: String,
    #[serde(rename = "type")]
    pub r#type: models::SyncEntityType,
}

impl SyncAckDto {
    pub fn new(ack: String, r#type: models::SyncEntityType) -> SyncAckDto {
        SyncAckDto {
            ack,
            r#type,
        }
    }
}

