/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAlbumV1 {
    /// Created at
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Album description
    #[serde(rename = "description")]
    pub description: String,
    /// Album ID
    #[serde(rename = "id")]
    pub id: String,
    /// Is activity enabled
    #[serde(rename = "isActivityEnabled")]
    pub is_activity_enabled: bool,
    /// Album name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "order")]
    pub order: models::AssetOrder,
    /// Owner ID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// Thumbnail asset ID
    #[serde(rename = "thumbnailAssetId", deserialize_with = "Option::deserialize")]
    pub thumbnail_asset_id: Option<String>,
    /// Updated at
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SyncAlbumV1 {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, description: String, id: String, is_activity_enabled: bool, name: String, order: models::AssetOrder, owner_id: String, thumbnail_asset_id: Option<String>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> SyncAlbumV1 {
        SyncAlbumV1 {
            created_at,
            description,
            id,
            is_activity_enabled,
            name,
            order,
            owner_id,
            thumbnail_asset_id,
            updated_at,
        }
    }
}

