/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncMemoryV1 {
    /// Created at
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Data
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, serde_json::Value>,
    /// Deleted at
    #[serde(rename = "deletedAt", deserialize_with = "Option::deserialize")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Hide at
    #[serde(rename = "hideAt", deserialize_with = "Option::deserialize")]
    pub hide_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Memory ID
    #[serde(rename = "id")]
    pub id: String,
    /// Is saved
    #[serde(rename = "isSaved")]
    pub is_saved: bool,
    /// Memory at
    #[serde(rename = "memoryAt")]
    pub memory_at: chrono::DateTime<chrono::FixedOffset>,
    /// Owner ID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// Seen at
    #[serde(rename = "seenAt", deserialize_with = "Option::deserialize")]
    pub seen_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Show at
    #[serde(rename = "showAt", deserialize_with = "Option::deserialize")]
    pub show_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "type")]
    pub r#type: models::MemoryType,
    /// Updated at
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SyncMemoryV1 {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, data: std::collections::HashMap<String, serde_json::Value>, deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>, hide_at: Option<chrono::DateTime<chrono::FixedOffset>>, id: String, is_saved: bool, memory_at: chrono::DateTime<chrono::FixedOffset>, owner_id: String, seen_at: Option<chrono::DateTime<chrono::FixedOffset>>, show_at: Option<chrono::DateTime<chrono::FixedOffset>>, r#type: models::MemoryType, updated_at: chrono::DateTime<chrono::FixedOffset>) -> SyncMemoryV1 {
        SyncMemoryV1 {
            created_at,
            data,
            deleted_at,
            hide_at,
            id,
            is_saved,
            memory_at,
            owner_id,
            seen_at,
            show_at,
            r#type,
            updated_at,
        }
    }
}

