/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAssetV2 {
    /// Checksum
    #[serde(rename = "checksum")]
    pub checksum: String,
    /// Uploaded to Immich at
    #[serde(rename = "createdAt", deserialize_with = "Option::deserialize")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Deleted at
    #[serde(rename = "deletedAt", deserialize_with = "Option::deserialize")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Duration
    #[serde(rename = "duration", deserialize_with = "Option::deserialize")]
    pub duration: Option<i32>,
    /// File created at
    #[serde(rename = "fileCreatedAt", deserialize_with = "Option::deserialize")]
    pub file_created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// File modified at
    #[serde(rename = "fileModifiedAt", deserialize_with = "Option::deserialize")]
    pub file_modified_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Asset height
    #[serde(rename = "height", deserialize_with = "Option::deserialize")]
    pub height: Option<i32>,
    /// Asset ID
    #[serde(rename = "id")]
    pub id: String,
    /// Is edited
    #[serde(rename = "isEdited")]
    pub is_edited: bool,
    /// Is favorite
    #[serde(rename = "isFavorite")]
    pub is_favorite: bool,
    /// Library ID
    #[serde(rename = "libraryId", deserialize_with = "Option::deserialize")]
    pub library_id: Option<String>,
    /// Live photo video ID
    #[serde(rename = "livePhotoVideoId", deserialize_with = "Option::deserialize")]
    pub live_photo_video_id: Option<String>,
    /// Local date time
    #[serde(rename = "localDateTime", deserialize_with = "Option::deserialize")]
    pub local_date_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Original file name
    #[serde(rename = "originalFileName")]
    pub original_file_name: String,
    /// Owner ID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// Stack ID
    #[serde(rename = "stackId", deserialize_with = "Option::deserialize")]
    pub stack_id: Option<String>,
    /// Thumbhash
    #[serde(rename = "thumbhash", deserialize_with = "Option::deserialize")]
    pub thumbhash: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::AssetTypeEnum,
    #[serde(rename = "visibility")]
    pub visibility: models::AssetVisibility,
    /// Asset width
    #[serde(rename = "width", deserialize_with = "Option::deserialize")]
    pub width: Option<i32>,
}

impl SyncAssetV2 {
    pub fn new(checksum: String, created_at: Option<chrono::DateTime<chrono::FixedOffset>>, deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>, duration: Option<i32>, file_created_at: Option<chrono::DateTime<chrono::FixedOffset>>, file_modified_at: Option<chrono::DateTime<chrono::FixedOffset>>, height: Option<i32>, id: String, is_edited: bool, is_favorite: bool, library_id: Option<String>, live_photo_video_id: Option<String>, local_date_time: Option<chrono::DateTime<chrono::FixedOffset>>, original_file_name: String, owner_id: String, stack_id: Option<String>, thumbhash: Option<String>, r#type: models::AssetTypeEnum, visibility: models::AssetVisibility, width: Option<i32>) -> SyncAssetV2 {
        SyncAssetV2 {
            checksum,
            created_at,
            deleted_at,
            duration,
            file_created_at,
            file_modified_at,
            height,
            id,
            is_edited,
            is_favorite,
            library_id,
            live_photo_video_id,
            local_date_time,
            original_file_name,
            owner_id,
            stack_id,
            thumbhash,
            r#type,
            visibility,
            width,
        }
    }
}

