/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAssetDeleteV1 {
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: String,
}

impl SyncAssetDeleteV1 {
    pub fn new(asset_id: String) -> SyncAssetDeleteV1 {
        SyncAssetDeleteV1 {
            asset_id,
        }
    }
}

