/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncUserV1 {
    #[serde(rename = "avatarColor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_color: Option<Option<models::UserAvatarColor>>,
    /// User deleted at
    #[serde(rename = "deletedAt", deserialize_with = "Option::deserialize")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// User has profile image
    #[serde(rename = "hasProfileImage")]
    pub has_profile_image: bool,
    /// User ID
    #[serde(rename = "id")]
    pub id: String,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// User profile changed at
    #[serde(rename = "profileChangedAt")]
    pub profile_changed_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SyncUserV1 {
    pub fn new(deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>, email: String, has_profile_image: bool, id: String, name: String, profile_changed_at: chrono::DateTime<chrono::FixedOffset>) -> SyncUserV1 {
        SyncUserV1 {
            avatar_color: None,
            deleted_at,
            email,
            has_profile_image,
            id,
            name,
            profile_changed_at,
        }
    }
}

