/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncUserMetadataV1 {
    #[serde(rename = "key")]
    pub key: models::UserMetadataKey,
    /// User ID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// User metadata value
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl SyncUserMetadataV1 {
    pub fn new(key: models::UserMetadataKey, user_id: String, value: std::collections::HashMap<String, serde_json::Value>) -> SyncUserMetadataV1 {
        SyncUserMetadataV1 {
            key,
            user_id,
            value,
        }
    }
}

