/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyncRequestType : Sync request type
/// Sync request type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncRequestType {
    #[serde(rename = "AlbumsV1")]
    AlbumsV1,
    #[serde(rename = "AlbumsV2")]
    AlbumsV2,
    #[serde(rename = "AlbumUsersV1")]
    AlbumUsersV1,
    #[serde(rename = "AlbumToAssetsV1")]
    AlbumToAssetsV1,
    #[serde(rename = "AlbumAssetsV1")]
    AlbumAssetsV1,
    #[serde(rename = "AlbumAssetsV2")]
    AlbumAssetsV2,
    #[serde(rename = "AlbumAssetExifsV1")]
    AlbumAssetExifsV1,
    #[serde(rename = "AssetsV1")]
    AssetsV1,
    #[serde(rename = "AssetsV2")]
    AssetsV2,
    #[serde(rename = "AssetExifsV1")]
    AssetExifsV1,
    #[serde(rename = "AssetEditsV1")]
    AssetEditsV1,
    #[serde(rename = "AssetMetadataV1")]
    AssetMetadataV1,
    #[serde(rename = "AuthUsersV1")]
    AuthUsersV1,
    #[serde(rename = "MemoriesV1")]
    MemoriesV1,
    #[serde(rename = "MemoryToAssetsV1")]
    MemoryToAssetsV1,
    #[serde(rename = "PartnersV1")]
    PartnersV1,
    #[serde(rename = "PartnerAssetsV1")]
    PartnerAssetsV1,
    #[serde(rename = "PartnerAssetsV2")]
    PartnerAssetsV2,
    #[serde(rename = "PartnerAssetExifsV1")]
    PartnerAssetExifsV1,
    #[serde(rename = "PartnerStacksV1")]
    PartnerStacksV1,
    #[serde(rename = "StacksV1")]
    StacksV1,
    #[serde(rename = "UsersV1")]
    UsersV1,
    #[serde(rename = "PeopleV1")]
    PeopleV1,
    #[serde(rename = "AssetFacesV1")]
    AssetFacesV1,
    #[serde(rename = "AssetFacesV2")]
    AssetFacesV2,
    #[serde(rename = "UserMetadataV1")]
    UserMetadataV1,

}

impl std::fmt::Display for SyncRequestType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AlbumsV1 => write!(f, "AlbumsV1"),
            Self::AlbumsV2 => write!(f, "AlbumsV2"),
            Self::AlbumUsersV1 => write!(f, "AlbumUsersV1"),
            Self::AlbumToAssetsV1 => write!(f, "AlbumToAssetsV1"),
            Self::AlbumAssetsV1 => write!(f, "AlbumAssetsV1"),
            Self::AlbumAssetsV2 => write!(f, "AlbumAssetsV2"),
            Self::AlbumAssetExifsV1 => write!(f, "AlbumAssetExifsV1"),
            Self::AssetsV1 => write!(f, "AssetsV1"),
            Self::AssetsV2 => write!(f, "AssetsV2"),
            Self::AssetExifsV1 => write!(f, "AssetExifsV1"),
            Self::AssetEditsV1 => write!(f, "AssetEditsV1"),
            Self::AssetMetadataV1 => write!(f, "AssetMetadataV1"),
            Self::AuthUsersV1 => write!(f, "AuthUsersV1"),
            Self::MemoriesV1 => write!(f, "MemoriesV1"),
            Self::MemoryToAssetsV1 => write!(f, "MemoryToAssetsV1"),
            Self::PartnersV1 => write!(f, "PartnersV1"),
            Self::PartnerAssetsV1 => write!(f, "PartnerAssetsV1"),
            Self::PartnerAssetsV2 => write!(f, "PartnerAssetsV2"),
            Self::PartnerAssetExifsV1 => write!(f, "PartnerAssetExifsV1"),
            Self::PartnerStacksV1 => write!(f, "PartnerStacksV1"),
            Self::StacksV1 => write!(f, "StacksV1"),
            Self::UsersV1 => write!(f, "UsersV1"),
            Self::PeopleV1 => write!(f, "PeopleV1"),
            Self::AssetFacesV1 => write!(f, "AssetFacesV1"),
            Self::AssetFacesV2 => write!(f, "AssetFacesV2"),
            Self::UserMetadataV1 => write!(f, "UserMetadataV1"),
        }
    }
}

impl Default for SyncRequestType {
    fn default() -> SyncRequestType {
        Self::AlbumsV1
    }
}

