/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAssetFaceDeleteV1 {
    /// Asset face ID
    #[serde(rename = "assetFaceId")]
    pub asset_face_id: String,
}

impl SyncAssetFaceDeleteV1 {
    pub fn new(asset_face_id: String) -> SyncAssetFaceDeleteV1 {
        SyncAssetFaceDeleteV1 {
            asset_face_id,
        }
    }
}

