/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncStreamDto {
    /// Reset sync state
    #[serde(rename = "reset", skip_serializing_if = "Option::is_none")]
    pub reset: Option<bool>,
    /// Sync request types
    #[serde(rename = "types")]
    pub types: Vec<models::SyncRequestType>,
}

impl SyncStreamDto {
    pub fn new(types: Vec<models::SyncRequestType>) -> SyncStreamDto {
        SyncStreamDto {
            reset: None,
            types,
        }
    }
}

