/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAssetEditV1 {
    #[serde(rename = "action")]
    pub action: models::AssetEditAction,
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: String,
    /// Edit ID
    #[serde(rename = "id")]
    pub id: String,
    /// Edit parameters
    #[serde(rename = "parameters")]
    pub parameters: std::collections::HashMap<String, serde_json::Value>,
    /// Edit sequence
    #[serde(rename = "sequence")]
    pub sequence: i32,
}

impl SyncAssetEditV1 {
    pub fn new(action: models::AssetEditAction, asset_id: String, id: String, parameters: std::collections::HashMap<String, serde_json::Value>, sequence: i32) -> SyncAssetEditV1 {
        SyncAssetEditV1 {
            action,
            asset_id,
            id,
            parameters,
            sequence,
        }
    }
}

