/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAssetFaceV1 {
    /// Asset ID
    #[serde(rename = "assetId")]
    pub asset_id: String,
    /// Bounding box X1
    #[serde(rename = "boundingBoxX1")]
    pub bounding_box_x1: i32,
    /// Bounding box X2
    #[serde(rename = "boundingBoxX2")]
    pub bounding_box_x2: i32,
    /// Bounding box Y1
    #[serde(rename = "boundingBoxY1")]
    pub bounding_box_y1: i32,
    /// Bounding box Y2
    #[serde(rename = "boundingBoxY2")]
    pub bounding_box_y2: i32,
    /// Asset face ID
    #[serde(rename = "id")]
    pub id: String,
    /// Image height
    #[serde(rename = "imageHeight")]
    pub image_height: i32,
    /// Image width
    #[serde(rename = "imageWidth")]
    pub image_width: i32,
    /// Person ID
    #[serde(rename = "personId", deserialize_with = "Option::deserialize")]
    pub person_id: Option<String>,
    /// Source type
    #[serde(rename = "sourceType")]
    pub source_type: String,
}

impl SyncAssetFaceV1 {
    pub fn new(asset_id: String, bounding_box_x1: i32, bounding_box_x2: i32, bounding_box_y1: i32, bounding_box_y2: i32, id: String, image_height: i32, image_width: i32, person_id: Option<String>, source_type: String) -> SyncAssetFaceV1 {
        SyncAssetFaceV1 {
            asset_id,
            bounding_box_x1,
            bounding_box_x2,
            bounding_box_y1,
            bounding_box_y2,
            id,
            image_height,
            image_width,
            person_id,
            source_type,
        }
    }
}

