/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigGeneratedFullsizeImageDto {
    /// Enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "format")]
    pub format: models::ImageFormat,
    /// Progressive
    #[serde(rename = "progressive", skip_serializing_if = "Option::is_none")]
    pub progressive: Option<bool>,
    /// Quality
    #[serde(rename = "quality")]
    pub quality: i32,
}

impl SystemConfigGeneratedFullsizeImageDto {
    pub fn new(enabled: bool, format: models::ImageFormat, quality: i32) -> SystemConfigGeneratedFullsizeImageDto {
        SystemConfigGeneratedFullsizeImageDto {
            enabled,
            format,
            progressive: None,
            quality,
        }
    }
}

