/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigUserDto {
    /// Delete delay
    #[serde(rename = "deleteDelay")]
    pub delete_delay: i32,
}

impl SystemConfigUserDto {
    pub fn new(delete_delay: i32) -> SystemConfigUserDto {
        SystemConfigUserDto {
            delete_delay,
        }
    }
}

