/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigFFmpegDto {
    #[serde(rename = "accel")]
    pub accel: models::TranscodeHwAccel,
    /// Accelerated decode
    #[serde(rename = "accelDecode")]
    pub accel_decode: bool,
    /// Accepted audio codecs
    #[serde(rename = "acceptedAudioCodecs")]
    pub accepted_audio_codecs: Vec<models::AudioCodec>,
    /// Accepted containers
    #[serde(rename = "acceptedContainers")]
    pub accepted_containers: Vec<models::VideoContainer>,
    /// Accepted video codecs
    #[serde(rename = "acceptedVideoCodecs")]
    pub accepted_video_codecs: Vec<models::VideoCodec>,
    /// B-frames
    #[serde(rename = "bframes")]
    pub bframes: i32,
    #[serde(rename = "cqMode")]
    pub cq_mode: models::CqMode,
    /// CRF
    #[serde(rename = "crf")]
    pub crf: i32,
    /// GOP size
    #[serde(rename = "gopSize")]
    pub gop_size: i32,
    /// Max bitrate
    #[serde(rename = "maxBitrate")]
    pub max_bitrate: String,
    /// Preferred hardware device
    #[serde(rename = "preferredHwDevice")]
    pub preferred_hw_device: String,
    /// Preset
    #[serde(rename = "preset")]
    pub preset: String,
    /// References
    #[serde(rename = "refs")]
    pub refs: i32,
    #[serde(rename = "targetAudioCodec")]
    pub target_audio_codec: models::AudioCodec,
    /// Target resolution
    #[serde(rename = "targetResolution")]
    pub target_resolution: String,
    #[serde(rename = "targetVideoCodec")]
    pub target_video_codec: models::VideoCodec,
    /// Temporal AQ
    #[serde(rename = "temporalAQ")]
    pub temporal_aq: bool,
    /// Threads
    #[serde(rename = "threads")]
    pub threads: i32,
    #[serde(rename = "tonemap")]
    pub tonemap: models::ToneMapping,
    #[serde(rename = "transcode")]
    pub transcode: models::TranscodePolicy,
    /// Two pass
    #[serde(rename = "twoPass")]
    pub two_pass: bool,
}

impl SystemConfigFFmpegDto {
    pub fn new(accel: models::TranscodeHwAccel, accel_decode: bool, accepted_audio_codecs: Vec<models::AudioCodec>, accepted_containers: Vec<models::VideoContainer>, accepted_video_codecs: Vec<models::VideoCodec>, bframes: i32, cq_mode: models::CqMode, crf: i32, gop_size: i32, max_bitrate: String, preferred_hw_device: String, preset: String, refs: i32, target_audio_codec: models::AudioCodec, target_resolution: String, target_video_codec: models::VideoCodec, temporal_aq: bool, threads: i32, tonemap: models::ToneMapping, transcode: models::TranscodePolicy, two_pass: bool) -> SystemConfigFFmpegDto {
        SystemConfigFFmpegDto {
            accel,
            accel_decode,
            accepted_audio_codecs,
            accepted_containers,
            accepted_video_codecs,
            bframes,
            cq_mode,
            crf,
            gop_size,
            max_bitrate,
            preferred_hw_device,
            preset,
            refs,
            target_audio_codec,
            target_resolution,
            target_video_codec,
            temporal_aq,
            threads,
            tonemap,
            transcode,
            two_pass,
        }
    }
}

