/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigBackupsDto {
    #[serde(rename = "database")]
    pub database: Box<models::DatabaseBackupConfig>,
}

impl SystemConfigBackupsDto {
    pub fn new(database: models::DatabaseBackupConfig) -> SystemConfigBackupsDto {
        SystemConfigBackupsDto {
            database: Box::new(database),
        }
    }
}

