/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigNotificationsDto {
    #[serde(rename = "smtp")]
    pub smtp: Box<models::SystemConfigSmtpDto>,
}

impl SystemConfigNotificationsDto {
    pub fn new(smtp: models::SystemConfigSmtpDto) -> SystemConfigNotificationsDto {
        SystemConfigNotificationsDto {
            smtp: Box::new(smtp),
        }
    }
}

