/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigSmtpTransportDto {
    /// SMTP server hostname
    #[serde(rename = "host")]
    pub host: String,
    /// Whether to ignore SSL certificate errors
    #[serde(rename = "ignoreCert")]
    pub ignore_cert: bool,
    /// SMTP password
    #[serde(rename = "password")]
    pub password: String,
    /// SMTP server port
    #[serde(rename = "port")]
    pub port: i32,
    /// Whether to use secure connection (TLS/SSL)
    #[serde(rename = "secure")]
    pub secure: bool,
    /// SMTP username
    #[serde(rename = "username")]
    pub username: String,
}

impl SystemConfigSmtpTransportDto {
    pub fn new(host: String, ignore_cert: bool, password: String, port: i32, secure: bool, username: String) -> SystemConfigSmtpTransportDto {
        SystemConfigSmtpTransportDto {
            host,
            ignore_cert,
            password,
            port,
            secure,
            username,
        }
    }
}

