/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigStorageTemplateDto {
    /// Enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Hash verification enabled
    #[serde(rename = "hashVerificationEnabled")]
    pub hash_verification_enabled: bool,
    /// Template
    #[serde(rename = "template")]
    pub template: String,
}

impl SystemConfigStorageTemplateDto {
    pub fn new(enabled: bool, hash_verification_enabled: bool, template: String) -> SystemConfigStorageTemplateDto {
        SystemConfigStorageTemplateDto {
            enabled,
            hash_verification_enabled,
            template,
        }
    }
}

