/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigTemplateEmailsDto {
    /// Album invite template
    #[serde(rename = "albumInviteTemplate")]
    pub album_invite_template: String,
    /// Album update template
    #[serde(rename = "albumUpdateTemplate")]
    pub album_update_template: String,
    /// Welcome template
    #[serde(rename = "welcomeTemplate")]
    pub welcome_template: String,
}

impl SystemConfigTemplateEmailsDto {
    pub fn new(album_invite_template: String, album_update_template: String, welcome_template: String) -> SystemConfigTemplateEmailsDto {
        SystemConfigTemplateEmailsDto {
            album_invite_template,
            album_update_template,
            welcome_template,
        }
    }
}

