/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagBulkAssetsResponseDto {
    /// Number of assets tagged
    #[serde(rename = "count")]
    pub count: i32,
}

impl TagBulkAssetsResponseDto {
    pub fn new(count: i32) -> TagBulkAssetsResponseDto {
        TagBulkAssetsResponseDto {
            count,
        }
    }
}

