/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagResponseDto {
    /// Tag color (hex)
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Creation date
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Tag ID
    #[serde(rename = "id")]
    pub id: String,
    /// Tag name
    #[serde(rename = "name")]
    pub name: String,
    /// Parent tag ID
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// Last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Tag value (full path)
    #[serde(rename = "value")]
    pub value: String,
}

impl TagResponseDto {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, name: String, updated_at: chrono::DateTime<chrono::FixedOffset>, value: String) -> TagResponseDto {
        TagResponseDto {
            color: None,
            created_at,
            id,
            name,
            parent_id: None,
            updated_at,
            value,
        }
    }
}

