/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagUpsertDto {
    /// Tag names to upsert
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl TagUpsertDto {
    pub fn new(tags: Vec<String>) -> TagUpsertDto {
        TagUpsertDto {
            tags,
        }
    }
}

