/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagsResponse {
    /// Whether tags are enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Whether tags appear in web sidebar
    #[serde(rename = "sidebarWeb")]
    pub sidebar_web: bool,
}

impl TagsResponse {
    pub fn new(enabled: bool, sidebar_web: bool) -> TagsResponse {
        TagsResponse {
            enabled,
            sidebar_web,
        }
    }
}

