/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateResponseDto {
    /// Template HTML content
    #[serde(rename = "html")]
    pub html: String,
    /// Template name
    #[serde(rename = "name")]
    pub name: String,
}

impl TemplateResponseDto {
    pub fn new(html: String, name: String) -> TemplateResponseDto {
        TemplateResponseDto {
            html,
            name,
        }
    }
}

