/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrashResponseDto {
    /// Number of items in trash
    #[serde(rename = "count")]
    pub count: i32,
}

impl TrashResponseDto {
    pub fn new(count: i32) -> TrashResponseDto {
        TrashResponseDto {
            count,
        }
    }
}

