/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssetDto {
    /// Original date and time
    #[serde(rename = "dateTimeOriginal", skip_serializing_if = "Option::is_none")]
    pub date_time_original: Option<String>,
    /// Asset description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Mark as favorite
    #[serde(rename = "isFavorite", skip_serializing_if = "Option::is_none")]
    pub is_favorite: Option<bool>,
    /// Latitude coordinate
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// Live photo video ID
    #[serde(rename = "livePhotoVideoId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub live_photo_video_id: Option<Option<uuid::Uuid>>,
    /// Longitude coordinate
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// Rating in range [1-5], or null for unrated
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<i32>>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::AssetVisibility>,
}

impl UpdateAssetDto {
    pub fn new() -> UpdateAssetDto {
        UpdateAssetDto {
            date_time_original: None,
            description: None,
            is_favorite: None,
            latitude: None,
            live_photo_video_id: None,
            longitude: None,
            rating: None,
            visibility: None,
        }
    }
}

