/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserStatus : User status
/// User status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "removing")]
    Removing,
    #[serde(rename = "deleted")]
    Deleted,

}

impl std::fmt::Display for UserStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "active"),
            Self::Removing => write!(f, "removing"),
            Self::Deleted => write!(f, "deleted"),
        }
    }
}

impl Default for UserStatus {
    fn default() -> UserStatus {
        Self::Active
    }
}

