/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAdminCreateDto {
    #[serde(rename = "avatarColor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_color: Option<Option<models::UserAvatarColor>>,
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// Grant admin privileges
    #[serde(rename = "isAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// Send notification email
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<bool>,
    /// User password
    #[serde(rename = "password")]
    pub password: String,
    /// PIN code
    #[serde(rename = "pinCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pin_code: Option<Option<String>>,
    /// Storage quota in bytes
    #[serde(rename = "quotaSizeInBytes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quota_size_in_bytes: Option<Option<i32>>,
    /// Require password change on next login
    #[serde(rename = "shouldChangePassword", skip_serializing_if = "Option::is_none")]
    pub should_change_password: Option<bool>,
    /// Storage label
    #[serde(rename = "storageLabel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_label: Option<Option<String>>,
}

impl UserAdminCreateDto {
    pub fn new(email: String, name: String, password: String) -> UserAdminCreateDto {
        UserAdminCreateDto {
            avatar_color: None,
            email,
            is_admin: None,
            name,
            notify: None,
            password,
            pin_code: None,
            quota_size_in_bytes: None,
            should_change_password: None,
            storage_label: None,
        }
    }
}

