/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserMetadataKey : User metadata key
/// User metadata key
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserMetadataKey {
    #[serde(rename = "preferences")]
    Preferences,
    #[serde(rename = "license")]
    License,
    #[serde(rename = "onboarding")]
    Onboarding,

}

impl std::fmt::Display for UserMetadataKey {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Preferences => write!(f, "preferences"),
            Self::License => write!(f, "license"),
            Self::Onboarding => write!(f, "onboarding"),
        }
    }
}

impl Default for UserMetadataKey {
    fn default() -> UserMetadataKey {
        Self::Preferences
    }
}

