/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLicense {
    /// Activation date
    #[serde(rename = "activatedAt")]
    pub activated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Activation key
    #[serde(rename = "activationKey")]
    pub activation_key: String,
    /// License key (format: /^IM(SV|CL)(-[\\dA-Za-z]{4}){8}$/)
    #[serde(rename = "licenseKey")]
    pub license_key: String,
}

impl UserLicense {
    pub fn new(activated_at: chrono::DateTime<chrono::FixedOffset>, activation_key: String, license_key: String) -> UserLicense {
        UserLicense {
            activated_at,
            activation_key,
            license_key,
        }
    }
}

