/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateLibraryDto {
    /// Exclusion patterns (max 128)
    #[serde(rename = "exclusionPatterns", skip_serializing_if = "Option::is_none")]
    pub exclusion_patterns: Option<Vec<String>>,
    /// Import paths to validate (max 128)
    #[serde(rename = "importPaths", skip_serializing_if = "Option::is_none")]
    pub import_paths: Option<Vec<String>>,
}

impl ValidateLibraryDto {
    pub fn new() -> ValidateLibraryDto {
        ValidateLibraryDto {
            exclusion_patterns: None,
            import_paths: None,
        }
    }
}

