/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionCheckStateResponseDto {
    /// Last check timestamp
    #[serde(rename = "checkedAt", deserialize_with = "Option::deserialize")]
    pub checked_at: Option<String>,
    /// Release version
    #[serde(rename = "releaseVersion", deserialize_with = "Option::deserialize")]
    pub release_version: Option<String>,
}

impl VersionCheckStateResponseDto {
    pub fn new(checked_at: Option<String>, release_version: Option<String>) -> VersionCheckStateResponseDto {
        VersionCheckStateResponseDto {
            checked_at,
            release_version,
        }
    }
}

