/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowShareStepDto {
    /// Step configuration
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Step is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Step plugin method
    #[serde(rename = "method")]
    pub method: String,
}

impl WorkflowShareStepDto {
    pub fn new(config: Option<std::collections::HashMap<String, serde_json::Value>>, method: String) -> WorkflowShareStepDto {
        WorkflowShareStepDto {
            config,
            enabled: None,
            method,
        }
    }
}

