/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowCreateDto {
    /// Workflow description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Workflow enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Workflow name
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::WorkflowStepDto>>,
    #[serde(rename = "trigger")]
    pub trigger: models::WorkflowTrigger,
}

impl WorkflowCreateDto {
    pub fn new(trigger: models::WorkflowTrigger) -> WorkflowCreateDto {
        WorkflowCreateDto {
            description: None,
            enabled: None,
            name: None,
            steps: None,
            trigger,
        }
    }
}

