/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowShareResponseDto {
    /// Workflow description
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// Workflow name
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    /// Workflow steps
    #[serde(rename = "steps")]
    pub steps: Vec<models::WorkflowShareStepDto>,
    #[serde(rename = "trigger")]
    pub trigger: models::WorkflowTrigger,
}

impl WorkflowShareResponseDto {
    pub fn new(description: Option<String>, name: Option<String>, steps: Vec<models::WorkflowShareStepDto>, trigger: models::WorkflowTrigger) -> WorkflowShareResponseDto {
        WorkflowShareResponseDto {
            description,
            name,
            steps,
            trigger,
        }
    }
}

