/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowTrigger : Plugin trigger type
/// Plugin trigger type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowTrigger {
    #[serde(rename = "AssetCreate")]
    AssetCreate,
    #[serde(rename = "PersonRecognized")]
    PersonRecognized,

}

impl std::fmt::Display for WorkflowTrigger {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AssetCreate => write!(f, "AssetCreate"),
            Self::PersonRecognized => write!(f, "PersonRecognized"),
        }
    }
}

impl Default for WorkflowTrigger {
    fn default() -> WorkflowTrigger {
        Self::AssetCreate
    }
}

