/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_time_bucket`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimeBucketError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_time_buckets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimeBucketsError {
    UnknownValue(serde_json::Value),
}


/// Retrieve a string of all asset ids in a given time bucket.
pub async fn get_time_bucket(configuration: &configuration::Configuration, time_bucket: &str, album_id: Option<&str>, bbox: Option<&str>, is_favorite: Option<bool>, is_trashed: Option<bool>, key: Option<&str>, order: Option<models::AssetOrder>, order_by: Option<models::AssetOrderBy>, person_id: Option<&str>, slug: Option<&str>, tag_id: Option<&str>, user_id: Option<&str>, visibility: Option<models::AssetVisibility>, with_coordinates: Option<bool>, with_partners: Option<bool>, with_stacked: Option<bool>) -> Result<models::TimeBucketAssetResponseDto, Error<GetTimeBucketError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_time_bucket = time_bucket;
    let p_query_album_id = album_id;
    let p_query_bbox = bbox;
    let p_query_is_favorite = is_favorite;
    let p_query_is_trashed = is_trashed;
    let p_query_key = key;
    let p_query_order = order;
    let p_query_order_by = order_by;
    let p_query_person_id = person_id;
    let p_query_slug = slug;
    let p_query_tag_id = tag_id;
    let p_query_user_id = user_id;
    let p_query_visibility = visibility;
    let p_query_with_coordinates = with_coordinates;
    let p_query_with_partners = with_partners;
    let p_query_with_stacked = with_stacked;

    let uri_str = format!("{}/timeline/bucket", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_album_id {
        req_builder = req_builder.query(&[("albumId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bbox {
        req_builder = req_builder.query(&[("bbox", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_favorite {
        req_builder = req_builder.query(&[("isFavorite", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_trashed {
        req_builder = req_builder.query(&[("isTrashed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_key {
        req_builder = req_builder.query(&[("key", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_person_id {
        req_builder = req_builder.query(&[("personId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_slug {
        req_builder = req_builder.query(&[("slug", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_tag_id {
        req_builder = req_builder.query(&[("tagId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("timeBucket", &p_query_time_bucket.to_string())]);
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_visibility {
        req_builder = req_builder.query(&[("visibility", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_coordinates {
        req_builder = req_builder.query(&[("withCoordinates", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_partners {
        req_builder = req_builder.query(&[("withPartners", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_stacked {
        req_builder = req_builder.query(&[("withStacked", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TimeBucketAssetResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TimeBucketAssetResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTimeBucketError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve a list of all minimal time buckets.
pub async fn get_time_buckets(configuration: &configuration::Configuration, album_id: Option<&str>, bbox: Option<&str>, is_favorite: Option<bool>, is_trashed: Option<bool>, key: Option<&str>, order: Option<models::AssetOrder>, order_by: Option<models::AssetOrderBy>, person_id: Option<&str>, slug: Option<&str>, tag_id: Option<&str>, user_id: Option<&str>, visibility: Option<models::AssetVisibility>, with_coordinates: Option<bool>, with_partners: Option<bool>, with_stacked: Option<bool>) -> Result<Vec<models::TimeBucketsResponseDto>, Error<GetTimeBucketsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_album_id = album_id;
    let p_query_bbox = bbox;
    let p_query_is_favorite = is_favorite;
    let p_query_is_trashed = is_trashed;
    let p_query_key = key;
    let p_query_order = order;
    let p_query_order_by = order_by;
    let p_query_person_id = person_id;
    let p_query_slug = slug;
    let p_query_tag_id = tag_id;
    let p_query_user_id = user_id;
    let p_query_visibility = visibility;
    let p_query_with_coordinates = with_coordinates;
    let p_query_with_partners = with_partners;
    let p_query_with_stacked = with_stacked;

    let uri_str = format!("{}/timeline/buckets", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_album_id {
        req_builder = req_builder.query(&[("albumId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bbox {
        req_builder = req_builder.query(&[("bbox", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_favorite {
        req_builder = req_builder.query(&[("isFavorite", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_trashed {
        req_builder = req_builder.query(&[("isTrashed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_key {
        req_builder = req_builder.query(&[("key", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_person_id {
        req_builder = req_builder.query(&[("personId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_slug {
        req_builder = req_builder.query(&[("slug", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_tag_id {
        req_builder = req_builder.query(&[("tagId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_visibility {
        req_builder = req_builder.query(&[("visibility", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_coordinates {
        req_builder = req_builder.query(&[("withCoordinates", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_partners {
        req_builder = req_builder.query(&[("withPartners", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_stacked {
        req_builder = req_builder.query(&[("withStacked", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::TimeBucketsResponseDto&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::TimeBucketsResponseDto&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTimeBucketsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

